services:
  postgres:
    image: postgres:16
    container_name: postgres_infra
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - ../database/migrations:/docker-entrypoint-initdb.d
